### ISSUE TITLE
A question in pyEnsLib.py?

### ISSUE THREAD

**Issue by xiaohumengdie** [NCAR/PyCECT#7]
In the source code, i found a sentence described as follows:
abs(new_scores[i][j]) > opts_dict['sigMul'] * (sigma_scores_gm[i])  (in pyEnsLib.py)
in my opinion, abs(new_scores[i][j]-np.average(scores_gm,axis=1)) > opts_dict['sigMul']  *(sigma_scores_gm[i]). 
Am I right?

**Comment by allibco** [comment]
Sorry for not noticing this issue...

The new_scores have already been standardized in main() right before calling this function (pyEnsLib.comparePCAscores).  So the code is correct as is.  In pyCECT.py, we have:

#Calculate the PCA scores of the new run                                                                                                                                      
        new_scores,var_list,comp_std_gm=pyEnsLib.standardized(means,mu_gm,sigma_gm,loadings_gm,ens_var_name,opts_dict,ens_avg,me)

run_index,decision=pyEnsLib.comparePCAscores(ifiles,new_scores,sigma_scores_gm,opts_dict,me)
